name: pypi-upload

on: [push]
#on:
#  release:
#    types: [created]

# ${GITHUB_REF##*/}

jobs:
  manylinux-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2014_x86_64
      with:
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
        build-requirements: 'cmake'
        pip-wheel-args: '-w ./dist --no-deps'
    - name: Show dists
      run: |
        ls ./dist
