name: Build Test CMake

on:
  workflow_dispatch:

env:
  Python_Version: 3.9

jobs:
  build_cmake:
    name: Build wheels ${{ matrix.OS }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:       
        include:  
         - os: ubuntu-latest
         - os: macos-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{env.Python_Version}}
      - name: Python Cache Key
        shell: bash
        run: |
          echo $(which python) > /tmp/python_version.txt
      - name: Get pip cache dir
        shell: bash
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
           path: ${{ steps.pip-cache.outputs.dir }}
           key: ${{ runner.os }}-pip-${{ hashFiles('/tmp/python_version.txt') }}
           restore-keys: |
              ${{ runner.os }}-pip-
      - name: Update
        run: | 
         pip install --upgrade pip wheel setuptools build
      - name: Install Dep
        if: ${{matrix.os == 'macos-latest'}}
        run: | 
         pip install delocate
      - name: Build 
        run: |
          export MACOSX_DEPLOYMENT_TARGET=11
          export USE_OMP=True
          python -m build 
      - name: IMPORT
        working-directory: dist 
        run: |
          for w in *.whl; do pip install $w; done
          python -c 'import pprint; import openjij; pprint.pprint(dir(openjij), compact=True)'
      - name: IMPORT
        continue-on-error: true
        run: |
          python -c 'import pprint; import cxxjij; pprint.pprint(dir(cxxjij), compact=True)'
      - name: IMPORT
        run: |
          pip install --force-reinstall --upgrade openjij
          python -c 'import pprint; import openjij; pprint.pprint(dir(openjij), compact=True)'
      - name: IMPORT
        continue-on-error: true
        run: |
          python -c 'import pprint; import cxxjij; pprint.pprint(dir(cxxjij), compact=True)'
      #- name: Build 
     #   run: |
      #    python setup.py build --debug test
      - name: Delocate List
        if: ${{matrix.os == 'macos-latest'}}
        working-directory: dist 
        run: for w in *.whl; do delocate-listdeps --all --depending $w; done
      - name: Delocate List
        if: ${{matrix.os == 'macos-latest'}}
        working-directory: dist 
        run: |
          mkdir ../delocate
          for w in *.whl; delocate-wheel  --require-archs x86-64 -w ../delocate -v  $w; done
      - name: Delocate List
        if: ${{matrix.os == 'macos-latest'}}
        working-directory: delocate
        run: for w in *.whl; do delocate-listdeps --all --depending $w; done

        
           
