name: Wheel

on:
  workflow_dispatch:

env:
  Python_Version: 3.9

jobs:
  wheel:
    name: Build wheels macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{env.Python_Version}}
      - name: Python Cache Key
        shell: bash
        run: |
          echo $(which python) > /tmp/python_version.txt
      - name: Get pip cache dir
        shell: bash
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
           path: ${{ steps.pip-cache.outputs.dir }}
           key: ${{ runner.os }}-pip-${{ hashFiles('/tmp/python_version.txt') }}
           restore-keys: |
              ${{ runner.os }}-pip-
      - name: Update
        run: | 
         pip install --upgrade pip wheel setuptools build
      - name: Install Dep
        run: | 
         pip install delocate
      - name: Homebrew Key
        run: |
          echo $(brew --version) > /tmp/brew
      - name: Get Homebrew  cache dir
        shell: bash
        id: homebrew-cache
        run: |
          echo "::set-output name=dir::$(brew --cache)"
      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.homebrew-cache.outputs.dir }}/downloads/d471854cb45185fec96714280a89336020d68864a5b9dec9ec01d4de352c8131--libomp-12.0.0.bottle_manifest.json
            ${{ steps.homebrew-cache.outputs.dir }}/downloads/3078f02ebb837089d81ffcbd3b77b3f5cf4a45765dd44083a279e9086de05f38--libomp--12.0.0.catalina.bottle.tar.gz
          key: brew-${{ hashFiles('/tmp/brew') }}
          restore-keys: brew-
      - name: Install libomp
        run: |
         brew install libomp
      - name: Download OpenJij
        run: |
         mkdir wheel
         pip wheel --no-deps --wheel-dir wheel openjij 
      - name: Show
        run: |
          du -a ./wheel
      - name: Wheel Name
        working-directory: wheel
        id: wheel
        run: |
          for f in *.whl; do echo "::set-output name=wheel::$f"; done
      - name: Delocate List
        working-directory: wheel
        run: delocate-listdeps --all --depending ./${{steps.wheel.outputs.wheel}}
      - name: Unpack 
        shell: bash
        id: unpack
        run: | 
          set -eux
          python -m wheel unpack ./wheel/${{steps.wheel.outputs.wheel}} 
          WHEEL=${{steps.wheel.outputs.wheel}} 
          WHEEL_NAME=$(echo "${WHEEL}" | sed 's/\-cp3[m0-9]\+\-cp3[m0-9]\+\-.*/ /g')
          find . -type d -maxdepth 1 -path "*openjij*"
          UNPACK_DIR=$(find . -type d -maxdepth 1 -path "*${WHEEL_NAME}")
          echo "::set-output name=unpack::$UNPACK_DIR"
          du -a 
      - name: Copy libomp 
        run: | 
          set -eux
          otool -D /usr/local/opt/libomp/lib/libomp.dylib
          otool -L /usr/local/opt/libomp/lib/libomp.dylib
          cp /usr/local/opt/libomp/lib/libomp.dylib ./openjij-0.3.5/
      - name: Pack 
        continue-on-error: true
        run: |
          otool -L ./openjij-0.3.5/cxxjij.cpython-39-darwin.so
          otool -D ./openjij-0.3.5/cxxjij.cpython-39-darwin.so
          python -m wheel pack
